export const JWT = {
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRES_TEMP: 'JWT_EXPIRES_TEMP',
  JWT_EXPIRES_ACCESS: 'JWT_EXPIRES_ACCESS',
  JWT_EXPIRES_REFRESH: 'JWT_EXPIRES_REFRESH',
};

export const MESSAGE_SERVICE = {
  SMS_API_KEY: 'SMS_API_KEY',
  SMS_API_SECRET: 'SMS_API_SECRET',
  FROM_NUMBER: 'FROM_NUMBER',
  BETA_TEST_TO_NUMBER: 'BETA_TEST_TO_NUMBER',
};

export const VERIFICATION = {
  VERIFY_CODE_LENGTH: 'VERIFY_CODE_LENGTH',
  DAILY_VERIFY_REQUEST_LIMITS: 'DAILY_VERIFY_REQUEST_LIMITS',
  VERIFY_LIMITS: 'VERIFY_LIMITS',
  VERIFY_EXPIRES_MINUTES: 'VERIFY_EXPIRES_MINUTES',
};

export const GOOGLE_OAUTH = {
  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL: 'GOOGLE_CALLBACK_URL',
};

export const NAVER_OAUTH = {
  NAVER_CLIENT_ID: 'NAVER_CLIENT_ID',
  NAVER_CLIENT_SECRET: 'NAVER_CLIENT_SECRET',
  NAVER_CALLBACK_URL: 'NAVER_CALLBACK_URL',
};

export const KAKAO_OAUTH = {
  KAKAO_CLIENT_ID: 'KAKAO_CLIENT_ID',
  KAKAO_CLIENT_SECRET: 'KAKAO_CLIENT_SECRET',
  KAKAO_CALLBACK_URL: 'KAKAO_CALLBACK_URL',
};
