// 개발 환경
const NODE_ENV = 'NODE_ENV';

// DB 환경변수
const DB_TYPE = 'DB_TYPE';
const DB_HOST = 'DB_HOST';
const DB_PORT = 'DB_PORT';
const DB_USERNAME = 'DB_USERNAME';
const DB_PASSWORD = 'DB_PASSWORD';
const DB_DATABASE = 'DB_DATABASE';

// 정보입력요청 정책
const DAILY_REQUEST_INFO_LIMITS = 'DAILY_REQUEST_INFO_LIMITS';
const DAILY_REQUEST_INFO_RETRY_LIMITS = 'DAILY_REQUEST_INFO_RETRY_LIMITS';
const REQUEST_INFO_EXPIRE_DAYS = 'REQUEST_INFO_EXPIRE_DAYS';
const REQUEST_INFO_VALIDATION_LIMITS = 'REQUEST_INFO_VALIDATION_LIMITS';

// 네트워크 환경변수
const PROTOCOL = 'PROTOCOL';
const HOST = 'HOST';
const PORT = 'PORT';
const CLIENT_HOST = 'CLIENT_HOST';
const CLIENT_PORT = 'CLIENT_PORT';
const LOGIN_URI = 'LOGIN_URI';

// 메세지 coolsms API 키
const SMS_API_KEY = 'SMS_API_KEY';
const SMS_API_SECRET = 'SMS_API_SECRET';
const FROM_NUMBER = 'FROM_NUMBER';
const BETA_TEST_TO_NUMBER = 'BETA_TEST_TO_NUMBER';

// JWT
const JWT_SECRET = 'JWT_SECRET';
const JWT_EXPIRES_TEMP = 'JWT_EXPIRES_TEMP';
const JWT_EXPIRES_ACCESS = 'JWT_EXPIRES_ACCESS';
const JWT_EXPIRES_REFRESH = 'JWT_EXPIRES_REFRESH';

// JWT COOKIE KEY
const ACCESS_TOKEN_KEY = 'ACCESS_TOKEN_KEY';
const REFRESH_TOKEN_KEY = 'REFRESH_TOKEN_KEY';
const TEMPORAL_TOKEN_KEY = 'TEMPORAL_TOKEN_KEY';

//회원가입 문자 인증
const VERIFY_CODE_LENGTH = 'VERIFY_CODE_LENGTH';
const DAILY_VERIFY_REQUEST_LIMITS = 'DAILY_VERIFY_REQUEST_LIMITS';
const VERIFY_LIMITS = 'VERIFY_LIMITS';
const VERIFY_EXPIRES_MINUTES = 'VERIFY_EXPIRES_MINUTES';

//TEST 용 ADMIN 계정
const MOKJANG_ADMIN = 'MOKJANG_ADMIN';

//구글 로그인
const GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID';
const GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET';
const GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL';

//네이버 로그인
const NAVER_CLIENT_ID = 'NAVER_CLIENT_ID';
const NAVER_CLIENT_SECRET = 'NAVER_CLIENT_SECRET';
const NAVER_CALLBACK_URL = 'NAVER_CALLBACK_URL';

//카카오 로그인
const KAKAO_CLIENT_ID = 'KAKAO_CLIENT_ID';
const KAKAO_CLIENT_SECRET = 'KAKAO_CLIENT_SECRET';
const KAKAO_CALLBACK_URL = 'KAKAO_CALLBACK_URL';

export const ENV_VARIABLE_KEY = {
  // 개발 환경
  NODE_ENV,

  // DB 환경변수
  DB_TYPE,
  DB_HOST,
  DB_PORT,
  DB_USERNAME,
  DB_PASSWORD,
  DB_DATABASE,

  // 정보입력요청 정책
  DAILY_REQUEST_INFO_LIMITS,
  DAILY_REQUEST_INFO_RETRY_LIMITS,
  REQUEST_INFO_EXPIRE_DAYS,
  REQUEST_INFO_VALIDATION_LIMITS,

  // 네트워크 환경변수
  PROTOCOL,
  HOST,
  PORT,
  CLIENT_HOST,
  CLIENT_PORT,
  LOGIN_URI,

  // 메세지 coolsms API 키
  SMS_API_KEY,
  SMS_API_SECRET,
  FROM_NUMBER,
  BETA_TEST_TO_NUMBER,

  // JWT
  JWT_SECRET,
  JWT_EXPIRES_TEMP,
  JWT_EXPIRES_ACCESS,
  JWT_EXPIRES_REFRESH,

  // JWT COOKIE KEY
  ACCESS_TOKEN_KEY,
  REFRESH_TOKEN_KEY,
  TEMPORAL_TOKEN_KEY,

  // 회원가입 문자 인증
  VERIFY_CODE_LENGTH,
  DAILY_VERIFY_REQUEST_LIMITS,
  VERIFY_LIMITS,
  VERIFY_EXPIRES_MINUTES,

  // TEST 용 ADMIN
  MOKJANG_ADMIN,

  // 구글 로그인
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CALLBACK_URL,

  // 네이버 로그인
  NAVER_CLIENT_ID,
  NAVER_CLIENT_SECRET,
  NAVER_CALLBACK_URL,

  // 카카오 로그인
  KAKAO_CLIENT_ID,
  KAKAO_CLIENT_SECRET,
  KAKAO_CALLBACK_URL,
};
