export enum NotificationEvent {
  TASK_IN_CHARGE_ADDED = 'task.inCharge.added',
  TASK_IN_CHARGE_CHANGED = 'task.inCharge.changed',
  TASK_IN_CHARGE_REMOVED = 'task.inCharge.removed',
  TASK_REPORT_ADDED = 'task.report.added',
  TASK_REPORT_REMOVED = 'task.report.removed',
  TASK_STATUS_UPDATED = 'task.status.updated',
  TASK_DATA_UPDATED = 'task.data.updated',
  TASK_DELETED = 'task.deleted',

  VISITATION_IN_CHARGE_ADDED = 'visitation.inCharge.added',
  VISITATION_IN_CHARGE_REMOVED = 'visitation.inCharge.removed',
  VISITATION_IN_CHARGE_CHANGED = 'visitation.inCharge.changed',
  VISITATION_REPORT_ADDED = 'visitation.report.added',
  VISITATION_REPORT_REMOVED = 'visitation.report.removed',
  VISITATION_STATUS_UPDATED = 'visitation.status.updated',
  VISITATION_DATA_UPDATED = 'visitation.data.updated',
  VISITATION_DELETED = 'visitation.deleted',

  EDUCATION_SESSION_IN_CHARGE_ADDED = 'education.session.inCharge.added',
  EDUCATION_SESSION_IN_CHARGE_REMOVED = 'education.session.inCharge.removed',
  EDUCATION_SESSION_IN_CHARGE_CHANGED = 'education.session.inCharge.changed',
  EDUCATION_SESSION_REPORT_ADDED = 'education.session.report.added',
  EDUCATION_SESSION_REPORT_REMOVED = 'education.session.report.removed',
  EDUCATION_SESSION_STATUS_UPDATED = 'education.session.status.updated',
  EDUCATION_SESSION_DATA_UPDATED = 'education.session.meta.updated',
  EDUCATION_SESSION_DELETED = 'education.session.deleted',

  EDUCATION_TERM_IN_CHARGE_ADDED = 'education.term.inCharge.added',
  EDUCATION_TERM_IN_CHARGE_REMOVED = 'education.term.inCharge.removed',
  EDUCATION_TERM_IN_CHARGE_CHANGED = 'education.term.inCharge.changed',
  EDUCATION_TERM_REPORT_ADDED = 'education.term.report.added',
  EDUCATION_TERM_REPORT_REMOVED = 'education.term.report.removed',
  EDUCATION_TERM_STATUS_UPDATED = 'education.term.status.updated',
  EDUCATION_TERM_DATA_UPDATED = 'education.term.data.updated',
  EDUCATION_TERM_DELETED = 'education.term.deleted',
  EDUCATION_TERM_ENROLLMENT_UPDATED = 'education.term.enrollment.updated',

  CHURCH_UPDATED = 'church.updated',
  MANAGER_PERMISSION_UPDATED = 'manager.permission.updated',
  PERMISSION_TEMPLATE_UPDATED = 'permission.template.updated',

  WORSHIP_SESSION_CREATED = 'worship.session.created',
}
